#include <string>
#include <vector>

enum class Category {
    advice,        // Advice, proverbs, life lessons
    appearance,    // Appearance
    emotions,      // Emotions
    expressions,   // Expressions
    family,        // Family, marriage, relationships
    food,          // Food
    intelligence,  // Intelligence
    laziness,      // Laziness
    relationships, // Love, romance, partners
    money,         // Money
    personality,   // Personality
    surprise,      // Surprise, exclamations
    weather,       // Weather
    work,          // Work
    general        // Other
};

struct Saying {
    bool okForPoliteCompany;
    std::string text;
    std::string meaning;
    Category category;
};

const std::vector<Saying> southernSayings = {
    {true, "Hotter than a billy goat in a pepper patch", "It's unbearably hot and almost comically so", Category::weather},
    {true, "Colder than a well digger's behind in January", "It's freezing cold, often used during a sharp winter morning", Category::weather},
    {true, "It's so hot the hens are laying hard-boiled eggs", "A funny way to exaggerate the high temperature", Category::weather},
    {true, "It's raining like a cow peeing on a flat rock", "Describes a sudden heavy rain with a splashy and chaotic feel", Category::weather},
    {true, "Hotter than blue blazes", "Describes extremely hot Southern heat", Category::weather},
    {true, "So humid, I could wring out the air", "Describes the sticky, muggy humidity", Category::weather},
    {true, "The devil's beating his wife", "The sun is shining while it is raining at the same time.", Category::weather},
    {true, "Sweatin' like a sinner in church", "Used when someone is uncomfortably hot or nervous", Category::emotions},
    {true, "Don't know him from Adam's house cat", "Describing a stranger", Category::expressions},
    {true, "Feels like the Lord left the oven door open", "Used when the weather is oppressively hot and dry", Category::weather},
    {true, "About as useful as a screen door on a submarine", "A humorous way to say someone seems useless", Category::expressions},
    {true, "He's got more nerve than a bum tooth", "Describes someone who is bold or has no shame", Category::personality},
    {true, "She could start an argument in an empty house", "A drama stirrer or someone always picking a fight", Category::personality},
    {true, "He's slicker than a greased pig at a county fair", "Someone who's cunning or hard to catch figuratively", Category::personality},
    {true, "Prettier than a speckled pup under a red wagon", "Means someone is absolutely adorable and attractive", Category::appearance},
    {true, "Dumber than a bag of hammers", "Used to call someone foolish or unintelligent", Category::intelligence},
    {true, "Fixin' to", "This person is about to do something.", Category::expressions},
    {true, "Lower than a snake's belly in a ditch", "Refers to someone with no moral backbone", Category::expressions},
    {true, "Got a face for radio", "A backhanded way of saying someone isn't very photogenic", Category::appearance},
    {true, "Crazier than a sprayed roach", "Someone acting wildly or irrationally - Or: Crazier than a bed/bessie/betsy/june bug", Category::personality},
    {true, "Lazy as a hound dog on a porch swing", "Extremely lazy and content to stay idle", Category::laziness},
    {true, "Wouldn't hit a lick at a snake", "Describes someone who won't even make a slight effort", Category::laziness},
    {true, "Too lazy to scratch an itch", "Someone who refuses to do even basic tasks", Category::laziness},
    {true, "Rather climb a tree to tell a lie than stand on the ground and tell the truth", "A twist on laziness with deception added in", Category::personality},
    {true, "Moves slower than molasses in January", "Someone who takes his sweet time, and drags his feet!", Category::laziness},
    {true, "Can't be bothered unless there's gravy involved", "Only works if there's a personal payoff", Category::work},
    {true, "So lazy he'd rather sleep standing up than find a place to lie down", "Comically exaggerates someone's unwillingness to make effort", Category::laziness},
    {true, "If work was a fire, he'd freeze to death", "A jab at someone who avoids work at all costs", Category::laziness},
    {true, "Got a Ph.D. in doing nothing", "Humorous way to label someone professionally lazy", Category::laziness},
    {true, "Lazier than a toad on a lily pad", "Slow and stationary, just soaking up life", Category::laziness},
    {true, "He doesn't know come from sic 'em", "Completely clueless or lacking basic common sense", Category::intelligence},
    {true, "If brains were leather, he wouldn't have enough to saddle a June bug", "Extremely unintelligent", Category::intelligence},
    {true, "The porch light's on, but nobody's home", "Someone looks alert but isn't really mentally present", Category::intelligence},
    {true, "Sharp as a mashed potato sandwich", "A humorous insult for someone lacking intellect", Category::intelligence},
    {true, "One biscuit shy of a breakfast", "A subtle, funny way to say someone's a bit off mentally", Category::personality},
    {true, "Couldn't pour water out of a boot with instructions on the heel", "A humorous way to describe someone as incredibly incompetent or dim-witted", Category::intelligence},
    {true, "Not the brightest crayon in the box", "A gentle, humorous way to say someone isn't very smart or quick-witted", Category::intelligence},
    {true, "If ignorance was bliss, he'd be the happiest man alive", "Extremely uninformed or naive", Category::personality},
    {true, "Got the IQ of a pinecone", "Sarcastic way to say someone is intellectually lacking", Category::intelligence},
    {true, "Dumber than dirt", "Simple, blunt, and classic southern jab", Category::intelligence},
    {true, "Tighter than bark on a tree when it comes to money", "Very frugal or stingy", Category::money},
    {true, "Been rode hard and put up wet", "Someone who looks worn out or rough around the edges", Category::appearance},
    {true, "Family trees in some parts don't fork", "A joke about inbreeding or lack of diversity in relationships", Category::family},
    {true, "Nuttier than a fruitcake", "Used to describe an eccentric or unpredictable person", Category::personality},
    {true, "That boy's momma didn't raise no fool", "A way to say someone's smart or knows better", Category::intelligence},
    {true, "She's as high-maintenance as a show pony", "A partner or relative who requires a lot of attention", Category::personality},
    {false, "He's married, but the fence still has a few holes in it", "Suggesting infidelity or lack of commitment", Category::relationships},
    {true, "Kin to everybody and nobody at the same time", "Refers to someone who claims lots of relations, often loose ones", Category::family},
    {true, "Got more baggage than Atlanta airport", "Someone who comes with a lot of emotional history and drama", Category::relationships},
    {true, "More whipped than a bowl of mashed potatoes", "Someone overly submissive in a relationship", Category::relationships},
    {true, "Nervous as a long-tailed cat in a room full of rocking chairs", "Extremely anxious or jumpy", Category::emotions},
    {true, "Happy as a pig in slop", "To be completely content and satisfied", Category::emotions},
    {true, "Busy as a one-legged cat in a sandbox", "Overwhelmed or trying hard to manage a lot.", Category::work},
    {true, "Crooked as a dog's hind leg", "Refers to someone dishonest or shady", Category::personality},
    {true, "Uglier than a mud fence after a rainstorm", "A brutal way to call someone unattractive", Category::appearance},
    {true, "Like herding cats", "Trying to control a chaotic or unmanageable situation", Category::work},
    {true, "Like a possum playing dead", "Avoids problems or pretends not to notice them", Category::personality},
    {true, "Meaner than a skillet full of rattlesnakes", "Describes someone especially vicious or angry", Category::personality},
    {true, "More tricks than a squirrel in a corn crib", "Someone who's clever or sneaky", Category::personality},
    {true, "Runnin' around like a chicken with its head cut off", "Acting frantic or disorganized in an inefficient way", Category::expressions},
    {true, "Between a rock and a hard place", "Stuck in a situation where there are no good choices", Category::expressions},
    {true, "If it were raining soup, I'd get hit with a fork", "Nothing ever goes right for this person", Category::expressions},
    {true, "Tougher than a two-dollar steak", "Describes something or someone extremely resilient or hard to handle", Category::personality},
    {true, "I'm hanging on by a thread", "Barely managing to hold it together — mentally, emotionally, or financially", Category::emotions},
    {true, "This ain't my first rodeo", "A way to say you've been through hard times before or done this enough to be familiar with it", Category::expressions},
    {true, "That dog won't hunt", "The plan or idea won't work", Category::expressions},
    {true, "Up a creek without a paddle", "In a bad situation with no clear way out", Category::expressions},
    {true, "Tighter than Dick's hatband", "Extremely cheap or stingy or strange", Category::money},
    {true, "Squeezes a quarter so tight the eagle screams", "Vivid exaggeration of the tightwad's frugality. Variations: penny so hard, Abe Lincoln cries; nickel so tight the Indian cries", Category::money},
    {true, "She's got champagne taste on a beer budget", "Loves expensive things but can't afford them", Category::money},
    {true, "He works harder than a one-eyed dog in a smokehouse", "Someone who works extremely hard", Category::work},
    {true, "Got more money than sense", "Rich, but lacking good judgment", Category::money},
    {true, "Wouldn't give you the time of day unless it made him a nickel", "Very self-serving or greedy", Category::money},
    {true, "Busier than a termite in a sawmill", "Incredibly busy or industrious", Category::work},
    {true, "Spends money like it's going out of style", "Carelessly extravagant with money", Category::money},
    {true, "Tighter than a new pair of boots", "Can describe both stinginess and discomfort in spending", Category::money},
    {true, "Bless your heart", "Could be sympathy or a subtle way of calling you an idiot", Category::expressions},
    {true, "She's got a good personality", "Code for someone who isn't physically attractive", Category::appearance},
    {true, "He's not the sharpest knife in the drawer", "A gentle way of saying someone isn't intelligent", Category::intelligence},
    {true, "Well, that's one way to do it", "Passive-aggressive disapproval masked as openness", Category::expressions},
    {true, "He means well", "Someone who tries but often fails or messes things up", Category::personality},
    {true, "She's a handful!", "A polite way of saying someone's difficult and/or dramatic, and might include the word real in front of handful", Category::personality},
    {true, "He could eat corn through a picket fence", "Describes someone with gapped teeth", Category::appearance},
    {true, "Beats all I've ever seen", "That tops everything. Variations: beats all I ever did see, beats all, that beats all", Category::surprise},
    {true, "You'd have to water that idea for it to grow", "A humorous way of calling it a dumb idea", Category::intelligence},
    {true, "She's a real peach, with a pit", "She seems sweet but she has a mean streak", Category::personality},
    {true, "He's slicker than owl snot", "Describes someone charming and maybe too much so", Category::personality},
    {true, "She's sweeter than a June bug on a honeysuckle vine", "An adorable person with great behavior", Category::personality},
    {true, "He's been bit by the love bug", "Clearly smitten or falling in love", Category::relationships},
    {true, "She put a spell on him stronger than grandma's moonshine", "Deeply infatuated and under someone's charm", Category::relationships},
    {false, "Shacking up", "Living together without being married", Category::family},
    {true, "She could charm the socks off a rooster", "Very flirtatious", Category::personality},
    {true, "Well, I'll be", "Expressing pure and wide-eyed astonishment", Category::surprise},
    {true, "I'l be derned", "Expression of surprise", Category::surprise},
    {true, "Possum in a rosebush!", "Expression of surprise", Category::surprise},
    {true, "Would argue with a fence post", "This describes someone who is very argumentative, and annoyingly so", Category::personality},
    {true, "Like a hair on a biscuit", "Describes someone who is annoying or out of place", Category::personality},
    {true, "We're living in high cotton", "Experiencing a time of well being", Category::emotions},
    {true, "What's got you all cattywampus?", "Askew, disordered, or crooked", Category::emotions},
    {true, "He was three sheets to the wind", "He was intoxicated", Category::expressions},
    {true, "Over yonder", "A general direction, not a specific place, and it might not be within reach but generally within sight", Category::expressions},
    {true, "Hissy fit", "Sudden and childish outburst of anger or frustration and applied to adults for a humorous edge", Category::emotions},
    {true, "Quit bein' ugly", "This has nothing to do with looks - stop being mean, rude, or acting uncouth", Category::advice},
    {true, "That doesn't amount to a hill of beans", "Something of little importance or value", Category::expressions},
    {true, "Lord willing and if the creeks don't rise", "A phrase that means if God approves the plan and hoping for no frustrating events along the way", Category::advice},
    {true, "He's silly as all get-out", "Utmost silliness. Get-out is used in other ways in the South to mean to the utmost conceivable degree", Category::personality},
    {true, "If I had my druthers", "If I had my choice", Category::expressions},
    {true, "I'm finer than frog hair and not half as slick", "A funny response to 'How are you?'", Category::expressions},
    {true, "Don't try to plow through the stump", "Farm wisdom about choosing the wiser path instead of the hardest one", Category::advice},
    {true, "He was plumb tuckered out", "Extremely tired or exhausted - Plumb may be a general inensifier word using in other sayings", Category::expressions},
    {true, "You can catch more flies with honey than with vinegar", "A proverb about the power of persuasion sometimes used when someone is being 'ugly' in the southern sense", Category::advice},
    {true, "She thinks she's so high falutin'", "Very pretentious", Category::personality},
    {true, "Coke", "Not just referring to the soft drink but any carbonated soda", Category::expressions},
    {true, "Too big for his britches", "Someone obviously full of himself", Category::personality},
    {true, "Blowin' up a storm", "Southerners say this when the wind picks up and the skies get cloudy", Category::weather},
    {true, "I'm so full, I'm about to pop", "What you might hear from a Southerner after a hearty meal - also full as a tick may be used", Category::food},
    {true, "Y'all", "This is a common Southern contraction of you and all used in addressing two or more persons. \"All y'all\" is used for more than two.", Category::expressions},
    {true, "He thinks the sun comes up just to hear him crow", "Conceited", Category::personality},
    {true, "Til the cows come home", "Cows tend to take their time, so this means it could be all day or a long time at least", Category::expressions},
    {true, "Doohickey", "When a Southerner can't think of a particular name for something, it suddenly becomes a doohickey.", Category::expressions},
    {true, "Cornbread ain't done in the middle", "Describes someone who is off in some way", Category::personality},
    {true, "Fair is a place where pigs get judged", "This is used when you have to tell someone that life isn't always fair. 4H competitions at County and State Fairs are common throughout the South.", Category::advice},
    {true, "Tore up", "A person who is truly upset by something", Category::emotions},
    {true, "Don't have a dog in this fight", "This is heard from a Southerner who doesn't care one way or the other about the matter at hand", Category::expressions},
    {true, "A month of Sundays", "A very long time. It might be in reference to something like not visiting your mom for a while.", Category::expressions},
    {true, "Piddlin'", "A piddlin' is a small amount that's not worth bothering with. Someone who is piddlin' in the yard is wasting time and not doing much.", Category::laziness},
    {true, "Gimme some sugar", "What Grandma says when you pull in the driveway, pop out of the car, and come running. She's not looking for sweets; she wants a hug and a kiss.", Category::family},
    {true, "Well, I declare!", "A Southerner using this phrase could be declaring any number of things: surprise, dissent, happiness. The only requirement is to declare it loud and proud.", Category::surprise},
    {true, "Hush your mouth", "A Southerner might use this to tell someone to stop complaining or to be quiet. It's also used to tell someone to stop being a baby.", Category::expressions},
    {true, "I'll tell you what", "This is a point of emphasis and exclamation that often ends without any additional telling at all. It can also be the opening to striking a bargain, sharing a strongly held opinion, or offering a piece of advice you may or may not want to hear.", Category::surprise},
    {true, "I reckon", "This can mean -- I suppose, I think, or I imagine. It is a quintessential Southern phrase, said by friends and family on porches and in rocking chairs all across the South.", Category::expressions},
    {true, "It'll make ya wanna slap your mama", "Used to describe something that's so good that you might do something unthinkable or extreme as a result. It's often used to describe food that's insanely delicious.", Category::food},
    {true, "A rooster one day and a feather duster the next", "This is a Southerner's creative way of saying that you shouldn't crow like a rooster about your wealth and belonging today, because it could all disappear tomorrow.", Category::advice},
    {true, "He ain't got the sense God gave a goose", "This is another nice way to say that someone is lacking in brain power.", Category::intelligence},
    {true, "Pretty is as pretty does", "Similar to the phrase \"quit being ugly,\" this one alludes to what's on the inside, not the outside, that matters. The expression is a simple reminder, often given to children, to remind them to be kind to others and mind their manners.", Category::advice},
    {true, "Can't never could", "This is positive thinking, Southern style.", Category::advice},
    {true, "Preachin' to the choir", "something to quit doing when trying to convince someone who already agrees with you", Category::expressions},
    {true, "It'll all come out in the wash", "Like dirt and stains, worries and problems will wash away. Whatever is bothering you isn't serious, and it will eventually be resolved with no lasting effects and that means don't worry.", Category::advice},
    {true, "You can't make a silk purse out of a sow's ear", "No matter how hard you try, you just can't make something pretty out of something ugly.", Category::advice},
    {true, "It's raining cats and dogs!", "This means that it's a downpour and not that kittens and puppies are literally falling from the sky.", Category::weather},
    {true, "Aren't you precious?", "Likely full of sarcasm, unless directed toward an adorable child", Category::expressions},
    {true, "You're barking up the wrong tree", "When you're very much in the wrong, you might hear this, or this can be used is if someone is telling you to back off.", Category::expressions},
    {true, "Hold your horses", "to wait, slow down, or be patient before taking action", Category::advice},
    {true, "Who licked the red off your candy?", "asked when there is a wondering why the person is so upset", Category::emotions},
    {true, "My eyeballs are floating!", "When you want to express just how badly you need the restroom, but you don't want to say it, use this phrase instead!", Category::emotions},
    {true, "She's madder than a wet hen", "Someone is very angry and may need some time to cool down", Category::emotions},
    {false, "I been running all over hell's half acre", "When the Southerner's day included going to many more places than he originally wanted or planned", Category::expressions},
    {true, "She's got a mind like a steel trap, but it's rusted shut", "Intelligence doesn't matter if you're unwilling to use it", Category::intelligence},
    {false, "She's busier than a cat covering poop on a marble floor", "Don't mistake motion for progress", Category::work},
    {true, "Don't go to the devil for advice on how to fight temptation", "Be mindful of where you seek guidance and wisdom", Category::advice},
    {true, "She's happier than a pig in a sunflower patch", "Appreciate the simple joys in life", Category::emotions},
    {true, "He's running like a scalded dog", "Sometimes urgency is the best motivator", Category::work},
    {true, "That'll jar your preserves", "Be ready for unexpected surprises in life", Category::surprise},
    {true, "He's as lost as last year's Easter egg", "Keep track of what matters or you might lose it", Category::personality},
    {true, "She's sweeter than tea with a double dose of sugar", "Kindness never goes out of style", Category::personality},
    {true, "Jumpy as a frog on a hot skillet", "Try to learn to stay calm under pressure", Category::emotions},
    {true, "She's like a hen trying to crow", "Stay true to who you are, not who others want you to be", Category::advice},
    {true, "If it ain't broke, don't fix it", "Sometimes, simplicity is best", Category::advice},
    {true, "Diggin' a hole deeper than a gopher on double time", "Know when to stop making things worse. (also - faster than a gopher in springtime)", Category::advice},
    {true, "He's got more excuses than a dog has fleas", "Own your mistakes and don't try to justify them", Category::advice},
    {true, "He's as stubborn as a mule in a mud pit", "Flexibility is key to success", Category::personality},
    {true, "She's holdin' on tighter than a tick on a hound", "Know when to let go of things that no longer serve you", Category::advice},
    {true, "He's walkin' on thin ice in cowboy boots", "Be careful where you tread. However, sometimes, the best decisions are the ones that come with the most risk.", Category::advice},
    {true, "She's spreadin' gossip faster than butter on a hot biscuit", "Guard your words as they can travel swiftly", Category::personality},
    {true, "That idea's about as good as a screen door on a tornado shelter", "Think things through before acting on it", Category::advice},
    {true, "Don't let the tail wag the dog", "Keep control of your priorities", Category::advice},
    {true, "He's like a one-legged man in a butt-kicking contest", "Don't take on more than you can handle", Category::work},
    {true, "You can't make chicken salad out of chicken scratch", "Use quality resources for quality outcomes", Category::advice},
    {true, "He's as unpredictable as a bull in a china shop", "Be mindful of how your actions may impact others", Category::personality},
    {true, "She's shining brighter than a new penny in sunlight", "Confidence is an accessory to success", Category::expressions},
    {true, "She's got a heart bigger than the state of Texas", "Generosity enriches lives and strengthens communities", Category::personality},
    {true, "She's like a firecracker on the Fourth of July", "Enthusiasm and energy are contagious", Category::personality},
    {true, "That's a tough row to hoe", "Hard work pays off", Category::work},
    {true, "Tarnation", "Some believe this could be a mixture of eternal and damnation. This is usually said like, 'What in tarnation?' as being shocked or agitated by something.", Category::surprise},
    {true, "Hankering", "This means getting a strong desire for something like fried chicken", Category::expressions},
    {true, "Fair to middlin'", "This means doing all right, but not too good or bad - just in the middle", Category::expressions},
    {true, "Ugly as homemade sin", "This is something rather unsightly or unpleasant", Category::appearance},
    {true, "Fit as a fiddle", "In good health and spirits", Category::expressions},
    {true, "Knee-high to a grasshopper", "This is a hyperbolic expression meaning very young, as in I haven't seen him since he was knee-high to a grasshopper", Category::family},
    {true, "Happy as a lark", "This is someone or something that is very happy", Category::emotions},
    {false, "Drunker than Cooter Brown", "He was a real person who lived along the Mason-Dixon line during the civil war. As years went by and the reputation grew, his name became synonymous with someone who was always inebriated.", Category::expressions},
    {true, "Clean as a whistle", "Someone who is innocent or something is entirely clean and dirt-free, judging from its apppearance", Category::expressions},
    {true, "Scarce as hen's teeth", "Very rare or impossible to find. Hens do not have teeth.", Category::expressions},
    {true, "She's got more nerve than Carter's got liver pills", "Carters repped the pills so hard that a Southern saying spawned from the advertisements. The FTC forced a drop of the “liver“ portion of the ad in 1951, claiming it was deceptive. But the South doesn't really pay attention to history so the phrase stuck. Sometimes you hear the phrase without liver in it.", Category::personality},
    {true, "All hat and no cattle", "Being overly boastful about yourself without much to back it up", Category::personality},
    {false, "Don't kick a cow turd on a hot day", "Don't go asking for trouble. President Harry S. Truman is responsible for this hilariously colorful warning.", Category::advice},
    {true, "Don't know whether to scratch their watch or wind their butt", "Incredibly confused. The phrase is a little confusing itself, which only makes the point further.", Category::general},
    {false, "That's about as useful as tits on a bull", "Only female dairy cows produce milk. Male cows are called bulls. And even if you could 'milk anything with nipples,' bulls tend to be rather ornery. So, good luck with that.", Category::expressions},
    {true, "Buggy", "Shopping cart", Category::expressions},
    {true, "Used to could", "I used to be able to do that, now I can't", Category::expressions},
    {true, "Gussied up", "Dressed up or “snazzy” looking - not wearing jeans and a t-shirt.", Category::appearance},
    {true, "Snug as a bug in a rug", "Extremely comfortable", Category::emotions},
    {true, "Tan your hide", "Your'e up for a good whoopin' aka spanking", Category::family},
    {true, "Umpteen", "A lot or countless times", Category::expressions},
    {true, "Having a conniption", "Throwing a dramatic, overreactive fit. It's often over something small, but the reaction is anything but.", Category::emotions},
    {true, "Heavens to Betsy", "An exclamation of surprise or astonishment, often used when something unexpected happens", Category::surprise},
    {true, "She's as pretty as a peach", "This is a high compliment on appearance, meaning beautiful", Category::appearance},
    {true, "If mama ain't happy, ain't nobody happy", "The household's mood depends on the mother's happiness", Category::emotions},
    {true, "Don't get your drawers in a wad", "A gentle reminder not to get too worked up over something minor. It's our way of saying, “Calm down; it's not worth the fuss.”", Category::advice},
    {true, "Well, slap my knee and call me silly", "An expression of surprise or astonishment, typically in response to unexpected news", Category::surprise},
    {true, "Gully washer", "An intense, heavy rainstorm that causes water to rush through ditches and gullies, often leading to temporary flooding", Category::weather},
    {true, "That'll put hair on your chest", "A phrase used to describe something particularly strong or intense, often about food or drink that has a bold, powerful effect", Category::food},
    {true, "Kiss my grits and call it gravy", "A sassy way of dismissing someone's opinion or response to something you've done or said, signaling that you don't care what they think or say", Category::emotions},
    {true, "Butter my butt and call me a biscuit", "An expression of surprise or disbelief, similar to saying, “Well, I'll be!”", Category::surprise},
    {true, "Hog wild", "Thrilled or enthusiastic, often acting with unchecked excitement or energy", Category::emotions},
    {true, "Give it a whirl", "Encourages someone to try something, even if they're unsure how it will turn out", Category::advice},
    {true, "Hand to mouth", "Living with just enough to get by, often scraping together what's needed daily, with little to no extra for savings or luxuries", Category::money},
    {true, "Don't let the door hit ya where the good Lord split ya", "Please get out now as I don't care if the door hits you on the way out", Category::expressions},
    {true, "Like two peas in a pod", "These two people are inseparable and depend on each other for support and companionship.", Category::personality},
    {true, "Like water off a duck's back", "Hearing this phrase is a suggestion that you should let go of whatever ails you so it doesn't keep you soaked in anger or frustration for too long.", Category::advice},
    {true, "Christmas Eve gift!", "This is usually said on the morning of Dec. 24, with the goal of being the first person to say it. In some families, saying it can even result in receiving an extra gift, and may be a hug.", Category::family},
    {true, "He's got ants in his pants", "Restless or unable to sit still", Category::emotions},
    {true, "Sweet tea makes everything better", "Or it is a serious problem", Category::expressions},
    {true, "He's as cool as a cucumber", "Very calm and composed", Category::emotions},
    {true, "Let's blow this popsicle stand", "Let's leave this place quickly", Category::expressions},
    {true, "Gag a maggot", "A phrase used to describe something that is extremely unpleasant or disgusting", Category::surprise},
    {true, "Go whole hog", "To do something completely or wholeheartedly", Category::expressions},
    {true, "Hold your own", "To maintain one's position or status", Category::general},
    {true, "In a New York minute", "Very quickly or suddenly", Category::expressions},
    {true, "Like a chicken on a junebug", "Very eager or enthusiastic about something", Category::emotions},
    {true, "Fell out of the ugly tree and hit every branch on the way down", "Unattractive or very ill behaved", Category::appearance},
    {true, "It's like putting lipstick on a pig", "Superficial or cosmetic changes won't make something better, or different than what it is", Category::advice},
    {true, "What in the Sam Hill?", "An expression of surprise or disbelief", Category::surprise},
    {true, "I'll tell you how the cow ate the cabbage", "I'm about (fixin') to tell you like it is", Category::expressions},
    {true, "If you can't run with the big dogs, stay on the porch", "If you can't keep up with the best, don't try to compete", Category::advice},
    {true, "She's got more layers than an onion", "Someone who is complex and has many facets to their personality", Category::personality},
    {true, "As the crow flies", "The shortest route between two points", Category::expressions},
    {true, "He's as happy as a clam at high tide", "Very happy and content", Category::emotions},
    {true, "Don't throw the baby out with the bathwater", "Don't discard something valuable while getting rid of something unwanted", Category::advice},
    {true, "She's as sharp as a tack", "Very intelligent and quick-witted", Category::intelligence},
    {true, "He's as busy as a one-armed paperhanger", "Extremely busy, often with limited resources", Category::work},
    {true, "Like trying to nail jelly to a tree", "An impossible or very difficult task", Category::work},
    {true, "She's got a heart of gold", "Very kind and generous", Category::personality},
    {true, "About as helpful as a bump on a log", "Not very helpful at all", Category::expressions},
    {true, "Don't count your chickens before they hatch", "Don't assume something will happen before it actually does", Category::advice},
    {true, "They don't have a lick of sense", "No common sense at all is present", Category::intelligence},
    {true, "As old as Methuselah", "Very old", Category::personality},
    {true, "Uppity", "Snobby or snooty", Category::personality},
    {true, "Skedaddle", "Let's get out of here", Category::expressions},
    {true, "I've got a hitch in my giddy-up (or get-along)", "Some physical ailment is keeping you from moving like you need to", Category::personality},
    {true, "Bright eyed and bushy tailed", "Eager and alert", Category::personality},
    {true, "Fly off the handle", "Becomes angry quickly. Originated from the head flying off of a hammer", Category::personality},
    {true, "Whistle britches", "Person who draws a lot of attention or is strong willed similar to a smarty pants. Sometimes heard with 'ole' added in front", Category::personality},
    {true, "Fit to be tied", "So mad you should be restrained", Category::emotions},
    {true, "If it was a snake it woulda bit me!", "When what you're looking for is right in front of you", Category::surprise},
    {true, "Dadgummit, Dagnabit", "Polite curse words", Category::expressions},
    {true, "Get it while the gettin's good", "Do something while things are going well", Category::advice},
    {true, "There's more than one way to skin a cat", "There's more than one way to do things", Category::advice},
    {true, "Fish or cut bait", "Stop talking about it and take action", Category::advice},
    {true, "Tump", "Tip or turn over accidentally", Category::expressions},
    {true, "I ain't got diddly squat", "To have nothing", Category::money},
    {true, "You can't get blood from a turnip", "You can't get anything from someone who has nothing to give", Category::money},
    {true, "I didn't just fall off the turnip truck", "I'm not naive or easily fooled", Category::intelligence},
    {true, "Make hay while the sun shines", "Take advantage of opportunities when available", Category::advice},
    {true, "Stove up", "Sore or stiff", Category::expressions},
    {true, "Ruckus", "A commotion", Category::expressions},
    {true, "There's not a pot too crooked that a lid won't fit", "Southern positivity is expressed well with this one and means there's someone out there for everyone", Category::relationships},
    {true, "We're so poor, we can't afford to pay attention", "Southern way of expressing being very poor and often combined with \"when I was growing up\"", Category::money},
    {true, "Yes ma'am or yessir", "While these are only good manners, Southerners say this often", Category::expressions},
    {true, "Sho nuff", "Sure enough", Category::expressions},
    {true, "Close the door! You're letting all the good air out.", "Air conditioning is so valued in the South, and if you leave the door open too long, you will hear about it!", Category::weather},
    {true, "Well that's the pot calling the kettle black", "One person accuses another of a fault that the first person is also guilty of", Category::expressions},
    {true, "Eat up with the dumb", "The dumb is strong in that one", Category::intelligence},
    {true, "Like putting socks on a rooster", "Difficult or impossible", Category::work},
    {true, "Well goodness gracious", "Exclamation used to express surprise, shock, or mild dismay", Category::surprise},
    {true, "Crawdads", "Southerners call crawfish this and sometimes crawdaddies", Category::expressions},
    {true, "Ragamuffin", "If you look like a ragamuffin, you don't look good enough to leave the house", Category::appearance},
    {true, "The greatest thing since pockets in blue jeans", "This is a twist on the more common greatest thing since sliced bread, used to describe something particularly useful, clever, or innovative", Category::expressions},
    {true, "Slower than a Sunday afternoon", "Moving at a leisurely and peaceful pace", Category::laziness},
    {true, "He can't carry a tune in a bucket", "Someone who is a terrible singer", Category::personality},
    {true, "She's catty-cornered to common sense", "Lacks logic or is acting irrationally", Category::intelligence},
    {true, "Happy as a dead pig in the sunshine", "Content or satisfied, often used sarcastically", Category::emotions},
    {true, "Lit up like a Christmas tree", "Extremely excited or overly decorated", Category::emotions},
    {true, "Full of beans or full of baloney", "Full of nonsense. You might also hear, \"Don't believe him; he's full of baloney\" or that's a load of baloney", Category::expressions},
    {true, "Old as dirt", "Very old", Category::expressions},
    {false, "Ain't got a pot to piss in", "Very poor", Category::money},
    {true, "Wound up tighter than a two-dollar watch", "Extremely tense or stressed", Category::emotions},
    {true, "Sweet as pie", "Very kind or pleasant", Category::personality},
    {true, "That just don't cut the mustard", "That's not good enough or doesn't meet standards", Category::expressions},
    {true, "Living high on the hog", "Living in luxury or comfort", Category::expressions},
    {true, "It's too wet to plow", "An excuse for being unable to work, often used as a general delay", Category::work},
    {true, "Like a bump on a log", "Sitting idle or inactive", Category::laziness},
    {true, "She's got more twists than a mountain road", "Describes someone unpredictable or complicated", Category::personality},
    {true, "She thinks she's the only hen in the coop", "Believes they are the center of attention or special", Category::personality},
    {true, "Tough as nails", "Resilient and strong", Category::personality},
    {true, "Smooth as silk", "Very suave or polished in demeanor", Category::personality},
    {true, "Full as a tick", "Completely full after eating", Category::food},
    {true, "Talking a blue streak", "Speaking very quickly and non-stop", Category::expressions},
    {true, "Don't let the bedbugs bite", "A common bedtime well-wish", Category::expressions},
    {true, "Good gravy!", "An exclamation of surprise", Category::surprise},
    {true, "He couldn't find his way out of a paper bag", "Completely lost or incompetent", Category::intelligence},
    {true, "Dumb as a box of rocks", "Extremely unintelligent", Category::intelligence},
    {true, "You can put your boots in the oven, but that don't make 'em biscuits", "Just because something seems like something doesn't mean it is that thing", Category::advice},
    {true, "Don't get your feathers ruffled", "Don't get upset or agitated", Category::advice},
    {true, "Well, that just dills my pickle!", "Expression of annoyance or frustration", Category::surprise},
    {true, "Grinning like a mule eating briars", "Smiling widely, often smugly", Category::appearance},
    {true, "She's wound tighter than an eight-day clock", "Very tense or high-strung", Category::emotions},
    {true, "Sweeter than a Georgia peach", "Extremely sweet or pleasant", Category::personality},
    {true, "Hotter than a stolen tamale", "Very hot or under pressure", Category::weather},
    {false, "Cold as a witch's tit in a brass bra", "Extremely cold", Category::weather},
    {true, "That old boy's strong as an ox", "Very physically strong", Category::personality},
    {true, "Like a moth to a flame", "Drawn irresistibly to something", Category::relationships},
    {true, "You look like you've been dragged through a knothole backwards", "Disheveled or exhausted appearance", Category::appearance},
    {true, "Stick out like a sore thumb", "Very noticeable or conspicuous", Category::appearance},
    {true, "More fun than a barrel of monkeys", "Extremely fun or entertaining", Category::expressions},
    {true, "No spring chicken", "Not young anymore", Category::personality},
    {true, "Looks like something the cat dragged in", "Looks messy or unkempt", Category::appearance},
    {true, "Easy as pie", "Very easy to do", Category::work},
    {true, "Riding shotgun", "Sitting in the front passenger seat", Category::expressions},
    {true, "Doesn't have both oars in the water", "Mentally lacking or not thinking straight", Category::personality},
    {true, "Naked as a jaybird", "Completely naked", Category::expressions},
    {true, "Don't bite off more than you can chew", "Don't take on more than you can handle", Category::advice},
    {true, "Long in the tooth", "Old or aging", Category::personality},
    {true, "Like shooting fish in a barrel", "Extremely easy", Category::expressions},
    {true, "If wishes were horses, beggars would ride", "Wishing for something doesn't make it happen", Category::advice},
    {true, "More nervous than a turkey in November", "Extremely anxious", Category::emotions},
    {true, "Quick as lightning", "Very fast", Category::expressions},
    {true, "Like a fish out of water", "Feeling out of place or uncomfortable", Category::expressions},
    {true, "Can't see the forest for the trees", "Too focused on details to see the big picture", Category::expressions},
    {true, "Like putting the cart before the horse", "Doing things out of proper order", Category::expressions},
    {true, "Spittin' image", "Looking exactly like someone else", Category::family},
    {true, "Right as rain", "Everything is fine or correct", Category::expressions},
    {true, "Hootin' and hollerin'", "Making a lot of noise, usually in celebration", Category::emotions},
    {true, "Balled the jack", "To move very fast or go all out", Category::expressions},
    {true, "Flew the coop", "Left or escaped", Category::expressions},
    {true, "Rode off into the sunset", "Left for good or moved on", Category::expressions},
    {true, "Don't take any wooden nickels", "Don't be fooled or cheated", Category::advice},
    {true, "He's a few sandwiches short of a picnic", "Lacking intelligence", Category::intelligence},
    {true, "All show and no go", "Looks good but lacks substance", Category::appearance},
    {true, "Cuter than a button", "Extremely cute", Category::appearance},
    {true, "Howdy", "Hello", Category::expressions},
    {true, "Y'all come back now, ya hear?", "A friendly invitation to return", Category::expressions},
    {true, "Cut the lights", "Turn off the lights", Category::expressions},
    {true, "Carry you somewhere", "Drive you somewhere", Category::expressions},
    {true, "Mash the button", "Press the button", Category::expressions},
    {true, "Pocketbook", "Purse", Category::expressions},
    {true, "Supper", "Dinner", Category::food},
    {true, "Do what now?", "Excuse me? or What did you say?", Category::surprise},
    {true, "How's your mom 'n 'em?", "How is your family? Sometimes mom and them", Category::family},
    {true, "Lord have mercy!", "Expression of surprise or exasperation", Category::surprise},
    {true, "Bless it!", "Expression of sympathy or frustration", Category::surprise},
    {true, "Good night!", "Expression of surprise (not a goodbye)", Category::surprise},
    {true, "Land sakes!", "Expression of surprise or astonishment", Category::surprise},
    {true, "Oh my stars!", "Expression of surprise", Category::surprise},
    {true, "Well, I'll swan!", "Expression of shock or disbelief", Category::surprise},
    {true, "For crying out loud!", "Expression of frustration", Category::surprise},
    {true, "Lordy, Lordy!", "Expression of surprise or emphasis", Category::surprise},
    {false, "It's hotter than the hinges of hell", "It's extremely hot", Category::weather},
    {true, "Whatever floats your boat", "Whatever makes you happy", Category::emotions},
    {true, "Tickled pink", "Very pleased or delighted", Category::emotions},
    {true, "Sunday-go-to-meeting clothes", "Your best clothes", Category::appearance},
    {true, "Big ol'", "Big (used as an intensifier)", Category::expressions},
    {true, "Little bitty", "Very small", Category::expressions},
    {true, "Directly", "Soon or in a little while", Category::expressions},
    {true, "Don't get your tail feathers in a bunch", "Don't get upset", Category::emotions},
    {true, "At the end of my rope", "Frustrated or at my limit", Category::emotions},
    {true, "Two shakes of a lamb's tail", "Very quickly", Category::expressions},
    {true, "That's the way the cookie crumbles", "That's just how things happen", Category::expressions},
    {true, "Dead as a doornail", "Completely dead", Category::expressions},
    {false, "Grinnin' like a jackass eatin' briars", "Smiling widely, often in a silly or smug way", Category::appearance},
    {true, "In a coon's age", "In a very long time", Category::expressions},
    {true, "Gooder than grits", "Very good or excellent", Category::expressions},
    {false, "Don't make me open up a can of whoop-ass", "Don't provoke me to fight or punish you", Category::advice},
    {true, "Fine and dandy", "Everything is great", Category::expressions},
    {true, "The apple doesn't fall far from the tree", "Children resemble their parents", Category::family},
    {true, "Don't put all your eggs in one basket", "Don't risk everything on one thing", Category::advice},
    {true, "That'll preach!", "That's a great point or truth", Category::expressions},
    {true, "You don't say!", "Expression of surprise or interest", Category::surprise},
    {true, "He's mule-stubborn and twice as ornery", "Not only stubborn but also very difficult to deal with", Category::personality},
    {true, "Land o' Goshen!", "Expression of surprise. Goshen was the region in Egypt inhabited by the Israelites until the Exodus in the Bible.", Category::surprise},
    {true, "It's hot enough to pop corn on the stalk", "A humorous exaggeration describing extremely hot weather so intense it affects crops in the field", Category::weather},
    {true, "Fiddlesticks!", "Mild exclamation of annoyance", Category::surprise},
    {true, "Well, shut my mouth!", "Expression of surprise or disbelief", Category::surprise},
    {true, "Heavens above!", "Expression of surprise or exasperation", Category::surprise},
    {true, "Even a blind hog finds an acorn now and then", "Even someone inept or unlucky will sometimes succeed", Category::advice},
    {true, "Got your ears lowered", "Got a haircut", Category::expressions},
    {true, "Haulin' tail", "Moving very fast or rushing", Category::expressions},
    {true, "Ain't right", "Something's off about that person", Category::expressions},
    {true, "Holler at me", "Used in farewell saying like \"stay in touch\" or contact me when needed", Category::expressions},
    {true, "Maters", "Tomatoes. Also, potatoes may be called taters, and sometimes a banana is called a nanner.", Category::food},
    {true, "If you want the rainbow, you gotta put up with the rain", "You have to endure difficulties to enjoy the good times", Category::advice},
    {true, "Ill as a hornet", "Very angry or upset", Category::emotions},
    {true, "I could chew up nails and spit out a barbed wire fence", "Very angry or upset", Category::emotions},
    {true, "Bless your pea-pickin' little heart", "Variation of bless your heart and may be affectionate or sarcastic depending on context", Category::expressions},
    {true, "I can't win for losing", "Can't seem to succeed no matter what I do", Category::expressions},
    {true, "I'm as busy as a farmer with one hoe and two rattlesnakes", "Having too much to do with inadequate resources", Category::work},
    {true, "He could talk the dogs off a meat truck", "Very persuasive and charming", Category::personality},
    {true, "Mess of catfish", "Fried catfish is a staple of Southern food. A mess is enough to feed your family.", Category::food},
    {false, "Wait just a cotton pickin' minute", "This is a mild expletive to add emphasis without using damn", Category::expressions},
    {true, "Fer piece", "A significant distance - You might hear, \"Billy Bob's house is a fer piece. Git in the truck and I'll carry you there.\"", Category::expressions},
    {true, "More than you can shake a stick at", "An expression meaning a large amount or number of something", Category::expressions},
    {true, "What fer?", "Funny response to this is \"Cat fur, to make kitten britches.\"", Category::general},
    {true, "He may not be a chicken, but he has his henhouse ways", "Timid and cautious", Category::personality},
    {true, "He's riding a gravy train with biscuit wheels", "Lucky and comfortable", Category::expressions},
    {true, "He don't care what you call him as long as you call him to supper", "He loves to eat", Category::food},
    {true, "Good ole boy", "A term used to describe a man who is considered a traditional, down-to-earth Southerner. The term can be used affectionately as someone who embodies the Southern values and lifestyle, such as hospitality, loyalty, and a strong sense of community. But, it can be used in a more critical way to describe someone who is perceived as old-fashioned or resistant to change.", Category::expressions},
    {true, "Happy as a tick on a hound", "Extremely happy and content, often used to describe someone who is enjoying a situation or environment that suits them perfectly.", Category::emotions},
    {false, "She's got more curves than a country road", "Attractive and curvy figure as a compliment", Category::appearance},
    {true, "Scared as a cat at a dog pound", "Nervous, frightened, or anxious", Category::emotions},
    {true, "Makes a pressure cooker look calm", "Nervous, anxious, or under a lot of stress", Category::emotions},
    {true, "She could talk a coon right out of a tree", "Talkative with influence", Category::personality},
    {true, "Well, I'll be a monkey's uncle!", "Expression of great surprise", Category::surprise},
    {true, "Put a little paint on the barn", "Needs makeup applied", Category::appearance},
    {true, "Busier than a cow's tail in fly season", "Extremely busy or active", Category::work},
    {true, "Go around by Laura's house", "Take a longer or indirect route to get somewhere", Category::expressions},
    {true, "Now we're cookin' with grease", "Things are going well or progressing smoothly", Category::expressions},
    {true, "90 to nothing", "Moving very fast or at full speed to get things done", Category::expressions},
    {true, "Take a gander", "Look at something", Category::expressions},
    {true, "Jump the broomstick", "Get married", Category::relationships},
    {true, "As popular as a pole cat in a perfume factory", "Someone who is extremely unwelcome or highly disliked", Category::expressions},
    {true, "Were you raised in a barn?", "Close the door / You have no manners", Category::personality},
    {true, "Bet your boots", "Absolutely certain", Category::expressions},
    {true, "You ain't just whistlin' Dixie", "Someone is serious or not kidding around", Category::expressions},
    {true, "Rougher than a corn cob in an outhouse", "Unpleasant or painful situation to deal with", Category::expressions},
    {true, "Scarce as deviled eggs at a Baptist picnic", "Disappears quickly or is hard to come by", Category::food},
    {true, "Take your own sweet time", "Gentle and sarcastic way of expressing irritation at someone being slow", Category::laziness},
    {true, "No bigger than a minnow in a fishing pond", "Something disappointingly small", Category::expressions},
    {true, "I love you a bushel and a peck and a hug around the neck", "Quintessential, endearing Southernism used by parents and grandparents to children and loved ones", Category::family},
    {false, "It's hotter than two rabbits screwin' in a wool sock!", "Extremely hot weather", Category::weather},
    {true, "You're gonna have old and new-monia dressed like that!", "Scantily clad or inappropriate clothing", Category::surprise},
    {false, "He couldn't find his ass with both hands in his back pockets", "Someone who is completely clueless or incompetent in a given situation. \"And a flashlight\" may be added for a higher level.", Category::intelligence},
    {true, "Having a duck fit", "This means throwing a tantrum or having an emotional outburst at a higher level than a hissy fit. Sometimes this is used as dying duck fit.", Category::emotions},
    {true, "Sweet as tea and sharp as vinegar", "Someone who is kind and pleasant but also has a sharp or keen mind", Category::intelligence},
    {true, "Don't go airing your dirty laundry in public", "Don't reveal private matters or personal issues in front of others", Category::advice},
    {true, "Larrupin' good", "Describes food that is exceptionally delicious, tasty, or finger-lickin' good. Sometimes used and spelled as only larpin'", Category::food},
    {true, "Woolly booger", "A hairy, unkempt person, a monster/Sasquatch, or a fuzzy caterpillar", Category::general},
    {true, "Rurnt", "Really spoiled, broken, or beyond saving, whether it's food, a situation, or someone's manners", Category::expressions},
    {true, "Scat cat", "Said sometimes after someone sneezes. Some longer versions have \"get your tail out of the gravy\" or \"your tail's on fire\" added on.", Category::expressions},
    {true, "She's hot as a two-dollar pistol", "Extremely attractive", Category::relationships},
    {true, "We go together like country ham and red-eye gravy", "Close relationship or bond", Category::relationships},
    {true, "As sure as the vine twines around the stump, you're my darling sugar lump", "Sweet phrase of affection", Category::relationships},
    {true, "Aight", "All right", Category::expressions },
    {true, "Get back to my rat killin'", "This is about getting back to work or attending to one's business. It is sometimes said as a polite way to end a conversation with a long winded person and typically by saying, \"Well, I'll let you get back to your rat killin'\"", Category::expressions },
    {true, "The whole kit and caboodle", "All the parts or elements of something", Category::expressions },
    {true, "Enough to choke a horse", "An excessive amount", Category::expressions},
    {true, "Between you, me, and the fence post", "Hey, listen, but don't tell a soul about any of this", Category::expressions},
    {true, "Sick as a dog", "Very ill", Category::expressions}
};




